# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='cellphone',
            field=models.CharField(max_length=80, null=True, verbose_name='Número de celular'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='identification',
            field=models.CharField(max_length=100, null=True, verbose_name='Número de identificacion'),
        ),
    ]
