# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_connectiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConectionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, verbose_name='Nombre de usuario')),
                ('password', models.CharField(max_length=300, verbose_name='Contaseña')),
                ('dbname', models.CharField(max_length=300, verbose_name='Nombre de la base de datos')),
                ('host', models.CharField(max_length=300, verbose_name='Host')),
                ('dbtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ConnectionType', verbose_name='Tipo de base de datos')),
            ],
            options={
                'verbose_name': 'Datos de conexión',
                'verbose_name_plural': 'Datos de conexiones',
            },
        ),
    ]
