# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_conectiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='conectiondata',
            name='port',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Puerto'),
        ),
    ]
